### ISSUE TITLE
mp3 support for vocal names

### ISSUE THREAD

**Issue by bernhardsen** [kcapp/frontend#101]
It would be nice if it was possible to upload mp3 files for player vocal names.

**Comment by thordy** [comment]
The biggest issue with this is how to make it work together with the current text-to-speech implementation.

For example today we have things like
- {name} to throw first
- {leg number} leg, {name} to throw first, game on
- {Game shot in the {leg num} leg, {name}!
- etc

In the current implementation there is no way to add in a separate audio file in the middle of speaking, and trying to sync the speech, by first saying one line, then waiting until a file has finished playing, then saying the second line will be very hard. I'm also afraid that it will not sound very natural, as it will have pauses between the different parts etc.

I'm also assuming it would not take long until someone abuses this and adds in a full song being played over and over again, and we no longer can have nice things...

**Comment by bernhardsen** [comment]
We would either need a client side audio player, capable of handling "playlists", or server side merging of audio files into one audio file. Both very doable.

Both these solutions would solve pauses between clips, but yes, this will only sound as natural as the author of the clips makes it.

... and regarding abuse. Yeah, that's why I want it. (we probably want to do a check on max duration tho).

**Comment by thordy** [comment]
This will be supported in next version
