### ISSUE TITLE
Define which opponent bot should mimick

### ISSUE THREAD

**Issue by kollstrom** [kcapp/frontend#102]
It should be possible to define an opponent you want to practice against: `Emil` vs `Bot as Emil`
The leg results of the practice opponent is generated based on its all time stats. 

Where in the UI should this be? Its own page, or should the option for choosing a kcapp user as opponent show up in the `Game settings` module if the selected opponent is `Test user`?

**Comment by thordy** [comment]
Bots can now be defined based on skill and as mocking
