### ISSUE TITLE
Hotkey for checkout

### ISSUE THREAD

**Issue by runarost** [kcapp/frontend#109]
Add a key on the numpad (if a good choice is available)) that allows a scorer to instant-score a checkout for a player. If the player at the oche for example is on 34 or 50, pressing button X would give D17 or D25 as input.

Would serve as a very good enhancement in public matches with designated scorer as it removes delay from a player winning the leg until it's registered (doubles are typically slow to enter).

**Comment by thordy** [comment]
`55` was added as a instant-checkout option
