### ISSUE TITLE
In best of EVEN_NUMBER games with shootout, let winner of bull start last in shootout

### ISSUE THREAD

**Issue by runarost** [kcapp/frontend#118]
When a match that is _best of an even number of legs with shootout_ ends with a draw, we go to a shootout. The current setting seems to be that the player that won bull and starts the first leg also starts the shootout. However, in a shootout it's an advantage to throw **last**, not first.

Suggestion is to default so start list in shootout is reverse of start list in first leg (should work for all numbers of players, not just two player matches).

**Comment by thordy** [comment]
Solved in https://github.com/kcapp/api/commit/3dbc4a3aa1091d010ff50299a16b4bb1c40c9acb
