### ISSUE TITLE
Scores in Leg Result view of Shootout X01 matches start at start score of X01

### ISSUE THREAD

**Issue by runarost** [kcapp/frontend#119]
The results page for a shootout leg in a X01 Best of EVEN_NUMBER legs with shootout should show scores starting at 0. Currently it starts at whatever the starting score of the X01.

See screenshot, and example link (internal system that main developer has access to):
![image](https://user-images.githubusercontent.com/44499152/141299611-59d7f48e-3545-469e-829d-80b3318a94a6.png)
https://darts.sportradar.ag/legs/22091/result

**Comment by thordy** [comment]
Already fixed by @oveaurs in https://github.com/kcapp/api/pull/13, just not deployed yet
