### ISSUE TITLE
Alternative button layout for inputting throws for devices with smaller screens

### ISSUE THREAD

**Issue by lluni** [kcapp/frontend#121]
I find the the current button layout to input throws in X01 (I have not tested other game modes besides Tic-Tac-Toe) very practical but you need to be pretty accurate to press the correct button.
Especially on mobile but even on a tablet the buttons can be relatively small so you can miss them pretty easily and need to re-input throws.
A possible solution could be to have a second alternative (and more compact) button layout in which the double/triple scores are not separate buttons. Here you would need to click a double/triple button first and then the corresponding single score to input a double/triple throw but you could also deselect it if you pressed it accidentally.

For reference:
![kcapp_buttons](https://user-images.githubusercontent.com/36239317/148705244-bceedfdf-29cd-4200-b200-9fdac03e857d.png)

In the alternative layout the buttons would need to be wider to fill the screen width.

**Comment by thordy** [comment]
Hi @lluni, that should be possible to add. 
For reference, could you let me know what kind of device you are normally using?

I guess adding a button for `single`, `double` and `triple` makes sense though, in case you click something incorrect, and want to switch modifier after the fact. This would also be similar to what we do when scoring via numpad.

We also probably want a `undo`/`backspace` button to remove input or last throw.

Would you still prefer to have buttons as a new row above as shown, with `Single`,`Double`,`Triple`,`Backspace`?
Or would another column on the right (after `17`,`13`,`9`,`5`,`1`) with the buttons vertically be fine?

**Comment by lluni** [comment]
I usually use a Samsung Galaxy Tab A (2016), 10,1".

I think only `double`, `triple` and `undo` buttons would be enough if the double/triple buttons and/or the score buttons themselves could "light up" (e.g. the buttons get the same background-color as the double/triple scores in the existing layout) if the double/triple button is selected and return to their "normal look" if it is deselected. But having a separate `single` button would not be a problem.

I think I would prefer having the (`single`,) `double`, `triple` and `undo` buttons vertically because they could become too wide if they are in a new row above.

**Comment by thordy** [comment]
I did a quick attempt at adding a more compact button input like you suggested. I realized we don't need the double bull button, and made the `double` and `triple` toggle the state of all buttons like you suggested!

![simplified_buttons](https://user-images.githubusercontent.com/1622278/148786362-e07cf700-0ae7-4661-8a05-344322f58d8a.gif)

Let me know if this is what you had in mind

**Comment by lluni** [comment]
Yeah, this looks nice!
Thank you very much for doing this so quickly!

**Comment by thordy** [comment]
To allow switching between the `old` (wide) and `new` (compact) button input mode, I added a `configure` button to the menue, which brings up a modal dialog where you can choose which layout you prefer. This is stored onto the localstorage of your device, so it will persist, so no need to set it more than once 
![image](https://user-images.githubusercontent.com/1622278/148965144-70d9555a-0359-4375-b7a4-bde451b76dde.png)

Done in `develop` (1396001100172f79e823e2b91e31be235a7748e4) and available in latest [docker image](https://hub.docker.com/layers/kcapp/frontend/latest/images/sha256-4fb7445f7a912a43e2a4038e9656b7307cd7ba085471c2d77c2a4ae89d654ae0?context=explore)
