### ISSUE TITLE
Add options for check-in/out requirements (straight-in etc.)

### ISSUE THREAD

**Issue by jkledal** [kcapp/frontend#143]
Would it be possible to add an option to X01 (and possibly other relevant game modes too) to define the requirements to check in or out? I.e. straight in/out, double in/out, triple in/out, master in/out?

**Comment by thordy** [comment]
Regarding Outshot, this is already supported for game types like `Tic-Tac-Toe`, so should be possible to add for other types like x01 as well.
Not sure how soon I would be able to look into this though, but I'll put it on the backlog

**Comment by thordy** [comment]
Initial work on adding `ANY` and `MASTER` checkouts have been added in https://github.com/kcapp/frontend/commit/19de40b6e92b0a79b448521e373a077602cdf058, not tested much yet so any feedback welcome.

Regarding defining `check-in`, no work done on this yet, but will see if it's something to add in the future
