### ISSUE TITLE
Dropdown Menu in Tablet / Controller Mode out of Screen

### ISSUE THREAD

**Issue by pthoelken** [kcapp/frontend#147]
In the picture we can see the right dropdown menu goes out of screen. 

![image](https://github.com/kcapp/frontend/assets/12643853/10f979d3-c0db-4a67-9fee-b2f3d52a22e4)

We can fix this with the **following css**

```
left: initial;
right: 0;
```

![image](https://github.com/kcapp/frontend/assets/12643853/2542f384-f213-4b0d-a358-fff8fd6666a9)

After apply this fix, the error seems to be gone. 

![image](https://github.com/kcapp/frontend/assets/12643853/1aa152fb-35e6-465a-bcc1-aa25077b24e7)

**Comment by thordy** [comment]
Thanks for the suggestion. Will be implemented in next release!
