### ISSUE TITLE
Pressing start game in a venue with "All" selected for Offices doesn't start leg

### ISSUE THREAD

**Issue by WallK** [kcapp/frontend#149]
STR:
1. Go to the main page of the app
2. Select 2 players
3. Select "All" in Offices block
4. Select venue
5. Press start

ER: Leg starts
AR: Page gets refreshed, URL changes to <app_address>/?, leg doesn't start

 
![chrome_2024-05-11_15-13-21](https://github.com/kcapp/frontend/assets/4513545/df731edb-1b08-4ee3-9d2e-eff8f9de11d6)

**Comment by thordy** [comment]
Hi @WallK , 
Thanks for reporting this, I thought this had been fixed a while back, but seems like it indeed wasn't.
I will try to find some time and get this resolved

**Comment by thordy** [comment]
Just pushed a fix for this issue 8a57c4f2eab27bcdbec70035976aeaf17da09aab
Let me know if you still have issues
