### ISSUE TITLE
Add % progress indicator to player profile page

### ISSUE THREAD

**Issue by Chmieloo** [kcapp/frontend#19]

**Comment by Chmieloo** [comment]
SELECT
    p.id AS 'player_id',
    COUNT(DISTINCT m.id) AS 'matches_played',
    COUNT(DISTINCT m2.id) AS 'matches_won',
    COUNT(DISTINCT l.id) AS 'legs_played',
    COUNT(DISTINCT l2.id) AS 'legs_won',
    SUM(s.ppd) / COUNT(p.id) AS 'ppd',
    SUM(s.first_nine_ppd) / COUNT(p.id) AS 'first_nine_ppd',
    SUM(s.60s_plus) AS '60s_plus',
    SUM(s.100s_plus) AS '100s_plus',
    SUM(s.140s_plus) AS '140s_plus',
    SUM(s.180s) AS '180s',
    SUM(s.accuracy_20) / COUNT(s.accuracy_20) AS 'accuracy_20s',
    SUM(s.accuracy_19) / COUNT(s.accuracy_19) AS 'accuracy_19s',
    SUM(s.overall_accuracy) / COUNT(s.overall_accuracy) AS 'accuracy_overall',
    COUNT(s.checkout_percentage) / SUM(s.checkout_attempts) * 100 AS 'checkout_percentage'
FROM statistics_x01 s
    JOIN player p ON p.id = s.player_id
    JOIN leg l ON l.id = s.leg_id
    JOIN matches m ON m.id = l.match_id
    LEFT JOIN leg l2 ON l2.id = s.leg_id AND l2.winner_id = p.id
    LEFT JOIN matches m2 ON m2.id = l2.match_id AND l2.winner_id = p.id
WHERE s.player_id IN (1)
    AND l.starting_score IN (301,501,701)
    AND l.is_finished = 1 AND m.is_abandoned = 0
    AND m.match_type_id = 1
    AND m.id NOT IN(SELECT MAX(match_id) FROM player2leg WHERE player_id IN(?) GROUP BY player_id ORDER BY match_id DESC)
GROUP BY s.player_id
ORDER BY p.id;

**Comment by thordy** [comment]
Done
