### ISSUE TITLE
Numpad selection on order-of-play dialog

### ISSUE THREAD

**Issue by runarost** [kcapp/frontend#32]
In the dialog where you select order of play you currently have to select each player with the mouse. In addition to be able to do that it should be possible to use the Numpad.

![image](https://user-images.githubusercontent.com/44499152/48229357-22a43d80-e3a8-11e8-9538-8250bf780d04.png)

**Comment by thordy** [comment]
Added in https://github.com/kcapp/frontend/commit/6ae5049b588740c157c47a6f2873ea7fff321466

Could definitely use some styling on the "buttons" (number on players displayed), but at least it works!
