### ISSUE TITLE
Allow easy opening of pages in new tabs

### ISSUE THREAD

**Issue by runarost** [kcapp/frontend#34]
Usually when you `Ctrl+Click` a link it will open in new tab. There are many places this doesn't work in kcapp, notably for `View` links:

![image](https://user-images.githubusercontent.com/44499152/48229933-b75b6b00-e3a9-11e8-8a28-0240a86d16d6.png)

And specifically for match report page, it's even impossible to right click and get `Open in new tab` choice:

![image](https://user-images.githubusercontent.com/44499152/48229981-d954ed80-e3a9-11e8-9d1b-f3619bd1438a.png)

**Comment by thordy** [comment]
This works correctly in tournament view, to both mouse middle click, ctrl+click and right click

**Comment by thordy** [comment]
Fixed in https://github.com/kcapp/frontend/commit/4881bc1f976459d349941c6985cb2ed2758377ad
