### ISSUE TITLE
Player tournament page

### ISSUE THREAD

**Issue by runarost** [kcapp/frontend#43]
When we click players in tournament view (in stats or in table) we should get to a new page. This new page should be under `Players --> Stats --> Tournaments --> Fall 2018` for example and be showing specific stuff for the player for **just that tournament**. Things the page should contain:

- Current table for the season for the division the player is in
- Results for player in the season
- Fixtures for player in the season
- Other tournament specific stats

**Comment by thordy** [comment]
Page added
