### ISSUE TITLE
More and better score announcements

### ISSUE THREAD

**Issue by runarost** [kcapp/frontend#48]
For special scores, we should add more soundclips from either professional announcers (for good scores), or funny effects (for funny effect on special scores, like 20-5-1, or 1-1-1).

An interesting idea is to have multiple sound clips per visitscore/visit-sequence-of-three-darts, and pick one at random.

**Comment by runarost** [comment]
A good tool to find which scores are the most interesting to add (if time is limited) is to make a query and see the most frequent 90+ scores since we started using kcapp.

**Comment by runarost** [comment]
At time of writing the biggest problem is the volume of "100". The volume is too low, and the tone of the announcer is a bit underwhelming for what a 100 means at lower levels.

**Comment by runarost** [comment]
Nice to have, it's a best effort thing where the more we add the better.

**Comment by runarost** [comment]
Remember to normalize volume across all sound clips.

**Comment by thordy** [comment]
> A good tool to find which scores are the most interesting to add (if time is limited) is to make a query and see the most frequent 90+ scores since we started using kcapp.

Here is a list of all scores `>=90` we have hit more than `20` times
```
| score | num  | 
|-------|------| 
| 100   | 1243 | 
| 95    | 266  | 
| 92    | 266  | 
| 98    | 214  | 
| 140   | 208  | 
| 90    | 160  | 
| 97    | 143  | 
| 99    | 129  | 
| 94    | 123  | 
| 96    | 122  | 
| 120   | 106  | 
| 125   | 99   | 
| 121   | 88   | 
| 93    | 86   | 
| 91    | 69   | 
| 101   | 60   | 
| 105   | 50   | 
| 116   | 36   | 
| 134   | 27   | 
| 135   | 26   | 
| 115   | 24   | 
| 137   | 24   | 
| 114   | 24   | 
| 118   | 23   | 
| 123   | 22   | 
| 132   | 21   | 
| 102   | 21   | 
```
