### ISSUE TITLE
Queue sound clips and voice announcements

### ISSUE THREAD

**Issue by runarost** [kcapp/frontend#49]
Currently we run into problems when there are multiple announcements/clips. Like if player A scores a big score followed by the other being on a checkout (and getting the "X, you require..." announcement). One might ruin the other if there's no break in between (or even overlap).

**Comment by thordy** [comment]
Fixed in https://github.com/kcapp/frontend/commit/f0922b9bdb30841e529c3ef674936a04a398e6b4
