### ISSUE TITLE
Missing voice announcements when on VPN

### ISSUE THREAD

**Issue by runarost** [kcapp/frontend#50]
Some voice announcements are lost because of timing issues when on VPN. In particular on game shot announcements.

**Comment by thordy** [comment]
I was unable to reproduce the issue we had when doing testing. But added a small delay on leg finish which hopefully solves it. We would need to test again where the tournament will be, and possibly increase this delay some more if it's still missing (https://github.com/kcapp/frontend/commit/c8f06b5f4756b52308959c004bb4acfd2815f342)
