### ISSUE TITLE
Match-switching in compact venue spectate mode

### ISSUE THREAD

**Issue by runarost** [kcapp/frontend#51]
We need a better way to switch between matches in spectate mode. Currently we don't switch matches until the first visit of the next match is over.

**Comment by runarost** [comment]
Possibly feature in #33 can help with this.

**Comment by runarost** [comment]
Should also be mentioned that with information screens between matches and possible stream overlay integration this might be needed as a manual process anyway.

**Comment by thordy** [comment]
Added proper switching on `warmup` signal in `OBS` and `Compact Spectate` mode
