### ISSUE TITLE
Remove leg stats page between legs in active matches

### ISSUE THREAD

**Issue by runarost** [kcapp/frontend#57]
Leg statistics is only interesting after a match has been played. Not during a match. Go straight from "X won the Nth leg" popup to the next leg.

**Comment by runarost** [comment]
Should be low effort, but isn't!!!

**Comment by thordy** [comment]
Looked into this, it is actually quite low effort and would be quick to fix, so it would just be to decide to do this.
It would be a global change affecting all matches, so just something we need to agree to do

**Comment by runarost** [comment]
I think we all agree to do this now. The playoffs *very clearly* showed that this is the way to go.

**Comment by thordy** [comment]
Done
