### ISSUE TITLE
Playoffs infopage - Schedule

### ISSUE THREAD

**Issue by runarost** [kcapp/frontend#58]
Make an information page containing entire schedule for the playoffs day (with all matches, for all divisions).

**Comment by runarost** [comment]
Evaluate possibility for brackets on this page too. Or consider splitting out into two schedule pages, one with matches listed, and one with all 3 brackets.

**Comment by thordy** [comment]
Related to https://github.com/kcapp/frontend/issues/61, since we now have a table containing `order_of_play` for all matches in a given tournament.

**Comment by thordy** [comment]
Example of schedule
![image](https://user-images.githubusercontent.com/1622278/48673484-3edf7180-eb42-11e8-9672-5cd264f7f404.png)

**Comment by thordy** [comment]
Added a very basic suggestion for schedule at `/tournaments/18/schedule`
Needs some styling and improvements

**Comment by thordy** [comment]
Closing as schedule is now added
