### ISSUE TITLE
Playoffs infopage - Match preview

### ISSUE THREAD

**Issue by runarost** [kcapp/frontend#61]
A match preview page (ideal to have as backdrop during walkons) containing some information about the players that meet each other. 

**Vital information is:**
- Player name
- Profile picture
- Best of X legs

**Ideally page should also have information about:**
- Matchname (like, "Prelimination final", "Grand final") and Division (so for example "Premier League - Grand Final")
- What the match means for winner/loser. This could be five things:
1. Winner is *Secured Trophy/Promotion*
2. Winner is *Qualified for Grand Final*
3. Winner is *Champion of the DIVISION*
4. Loser is *Eliminated in Nth place*
5. Loser is *Still alive and will play NAME_OF_MATCH against PLAYER_X*

**It would be magical to:**
Also show brackets within the division playoffs.

**Nice to have is:**
General stats, tournament stats, versus stats, all these are interesting as well.

**Comment by runarost** [comment]
This is probably the most important one to fix before the playoffs.

**Comment by runarost** [comment]
Attached list of playoff matches and some data about each and every one of them. With some smart coding and matches set up in advance with placeholder playerid before players have progressed, we can logically get away with the only maintenance being that we update playerids of upcoming matches when we know who progress.
[playoffsdata.zip](https://github.com/kcapp/frontend/files/2571020/playoffsdata.zip)

**Comment by thordy** [comment]
I have added a new endpoint to the backend which will load information about match metadata from the database. This gets information from a new table which can contain all the data suggested by Runar in above comment.
So now we just need to add a way to display this information in the frontend

**Comment by thordy** [comment]
![image](https://user-images.githubusercontent.com/1622278/48674307-f37d9100-eb4a-11e8-895a-485c22aa122f.png)

Information can be found from the new `/metadata` endpoint, and looks like this
```json
{
    "id": 1,
    "match_id": 3216,
    "order_of_play": 1,
    "tournament_group": {
        "id": 12,
        "name": "Conference",
        "division": null
    },
    "player_home": 3,
    "player_away": 21,
    "match_displayname": "Prelimination final",
    "elimination": true,
    "trophy": false,
    "promotion": false,
    "semi_final": false,
    "grand_final": false,
    "winner_outcome": "Qualified for Elimination final",
    "looser_outcome": "Eliminated in 26. place"
}
```

**Comment by runarost** [comment]
[Season 7.zip](https://github.com/kcapp/frontend/files/2592872/Season.7.zip)

Resource files for bracket stuff

**Comment by runarost** [comment]
[Fixed Display Structure.zip](https://github.com/kcapp/frontend/files/2592947/Fixed.Display.Structure.zip)

One arrow had an error. Attached is fixed version

**Comment by Chmieloo** [comment]
Change pushed to master.

**Comment by thordy** [comment]
Closing since preview now exist
