### ISSUE TITLE
FavIcon / Logo

### ISSUE THREAD

**Issue by thordy** [kcapp/frontend#62]
We should get a Logo made for kcapp which can also be used for FavIcon

**Comment by richardbmx** [comment]
@thordy Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by thordy** [comment]
@richardbmx Apologizes for not seeing (and responding) to this message sooner. If you want to create a favicon/logo, that would be more than welcome!

**Comment by richardbmx** [comment]
@thordy  Happy day I would like to present my proposal for the logo and favicon, inspired by the table of dardor I designed a part of it to give personality to the project and that simple view you see that it is additional to this I have added number to give the appearance counter, integrating in a very fluid way the text with the name Kcapp in two formats, vertical and horizontal which looks great, I hope you like it if you want some change you just have to request it and I will gladly do it

![Logo128](https://user-images.githubusercontent.com/35604837/55333919-2ffcba00-5466-11e9-87b9-ef0cc7debe25.png)

**Comment by thordy** [comment]
@richardbmx Thank you so much for these suggestions, they look great!
If it would be possible, could you make it so that the number next to "20" is actually a "1", like on a actual dartboard? And if possible make `kcapp` all lowercase. Also maybe a sample without the numbers would be great!
Thank you again for these great suggestinos!

**Comment by richardbmx** [comment]
@thordy  First I want to apologize for the delay I did not see your message and then you have some technical problems with the computer, here I leave you the changes and the variation without number if you want some change you should just ask for it I am focused on your project now

![Logo128modificado](https://user-images.githubusercontent.com/35604837/58183300-1cf3b280-7c7d-11e9-91a2-a1c17e83b078.png)

**Comment by thordy** [comment]
@richardbmx Thank you for creating edited version! They look great I think. Would it be possible to get them as individual files (also with transparent background) so I can integrate them into the project?

**Comment by richardbmx** [comment]
@thordy  
Perfect what version do you want the one that has the numbers or the one that does not have the numbers?

**Comment by thordy** [comment]
@richardbmx Would be great to get both, as I might use them in different areas, but I think the one without numbers looks great! 
Would also be nice to get one with only the logo (no text) in a smaller size I could use as favicon

**Comment by richardbmx** [comment]
@thordy   Happy day, delay the delay here I give you a folder of google drive with all the necessary files to integrate the logo to your project along with a copyright file so you can give free use to the logo without problems.

[Google Drive](https://drive.google.com/open?id=10Rln9K6y834bQt_UZF9sq1DXnWIsNBjy)

**Comment by richardbmx** [comment]
@thordy  Greetings have you managed to enter the folder with the logo designs?

**Comment by thordy** [comment]
@richardbmx My apologies for not getting back to you on this sooner, this project became a bit idle, and haven't had a chance to get back to it before now!
I was able to download all the suggestions you made, and they look great, thank you so much for creating them all! I will start integrating them into the project now!

Thank you so much again for your help!
