### ISSUE TITLE
New simple scoreboard mode for OBS

### ISSUE THREAD

**Issue by thordy** [kcapp/frontend#64]
We should create a scoreboard overlay which can be used for streams.

I suggest something like `/legs/id/obs`
Look at a PDC stream or Sportradar internal tournament stream to see examples of how the scoreboard could look

**Comment by runarost** [comment]
Including extra information popping up at defined intervals. Like `6` when players are on a six-darter. And popups for counting 26s or 100+s for example. This is next-step-stuff...

**Comment by thordy** [comment]
Done in https://github.com/kcapp/frontend/commit/855e472a4d66bbe4880f14fb7e0a1b4c64799cc0
