### ISSUE TITLE
Custom tiebreakers for tables

### ISSUE THREAD

**Issue by runarost** [kcapp/frontend#75]
It should be possible to have custom tiebreakers. Possible tie-breakers:

- Connected to a match (like a nine darts shootout that should get the official flag)
- Connected to a group of matches (like a three-man league played between tied players)
- A manual tiebreaker.

For SR Darts it's just the first one that is important.

**Comment by thordy** [comment]
I made it possible to set the `Offical` flag on `9 Dart Shootout` matches now
