### ISSUE TITLE
Add display name information

### ISSUE THREAD

**Issue by runarost** [kcapp/frontend#77]
We should have a property for display name in the player table:

This should mean we have the following information of the players:
1. Name: Their full name, with firstname and lastname
2. Nick: Their nickname
3. Vocalname: The name to be spoken during voice announcements. Typically just firstname, but with English variation to get pronunciation more similar to local language.
4. Displayname: Shortform to be shown various places, typically just firstname

```alter table `cakeapp_dev`.`player` 
   add column `displayname` varchar(255) CHARSET latin1 COLLATE latin1_swedish_ci NULL after nickname```

**Comment by runarost** [comment]
I'm going to fix names on staging database

**Comment by runarost** [comment]
Also need to add interface elements to set these properties

**Comment by thordy** [comment]
Won't add displayname, instead first and last name
