### ISSUE TITLE
Support for cancelling matches and manually adjust table

### ISSUE THREAD

**Issue by runarost** [kcapp/frontend#87]
In case none of the players play their league game in time for the deadline, and neither player made a reasonable attempt to get it played, the match is cancelled and scored as a loss for both players. This means we need two things:

1. Support for setting a match as "Cancelled" (or a better name). This should make the match impossible to play.
2. Support for manually adjusting table. Both players should have:
- +1 Played
- +1 Match loss
- +N Legs against (depends on division, for Trondheim Fall 2019 the options are `0-3` and `0-2`, so N=3 or N=2)

**Comment by thordy** [comment]
Relates to https://github.com/kcapp/frontend/issues/74
