### ISSUE TITLE
Add Calendar Support

### ISSUE THREAD

**Issue by thordy** [kcapp/frontend#89]
Would be nice to have an endpoint (in the API) which returns the tournament schedule for a given player.
Something like `/tournament/<id>/player/<id>/calendar` which returns a ics or similar with calendar events and reminders for all upcoming matches for the given player

**Comment by ingjardt** [comment]
I would suggest that an API call that gives you all events for a single player, regardless of tournament, would be useful. Then you would only have to add this to your calendar setup once, and not have to change anything for the new season.
