### ISSUE TITLE
Dart Vader's "Pending matches" should include today's matches

### ISSUE THREAD

**Issue by runarost** [kcapp/frontend#97]
In anticipation of #91 , how about a quickfix where the _date_ used for "Pending matches" is _tomorrow's date_ rather than _today's date_? Seems like we can have a 5m quickfix *some place* in the code where it's just a matter of adding a `someThing + 1`.

The result should be that today's matches is included in the list of pending matches.

**Comment by oveaurs** [comment]
didn't get to write someThing +1, but this is fairly close. Need testing.
